<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
  'key' => 'group_609972f83da29',
  'title' => 'Block: Three Column News',
  'fields' => array(
    array(
      'key' => 'field_609973038d5b2',
      'label' => 'Result Count',
      'name' => 'result_count',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 3,
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => 1,
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_60997726ab1f4',
      'label' => 'Filter by Category',
      'name' => 'filter_by_category',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'taxonomy' => 'category',
      'field_type' => 'radio',
      'allow_null' => 0,
      'add_term' => 1,
      'save_terms' => 0,
      'load_terms' => 0,
      'return_format' => 'id',
      'multiple' => 0,
    ),
    array(
      'key' => 'field_609978beba867',
      'label' => 'Card Height',
      'name' => 'card_height',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 600,
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array(
      'key' => 'field_609979c877357',
      'label' => 'Button Label',
      'name' => 'button_label',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Read More',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_6099e16546089',
      'label' => 'Card Color',
      'name' => 'card_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#ffffff',
    ),
    array(
      'key' => 'field_6099e4afe04d7',
      'label' => 'Card Title Color',
      'name' => 'card_title_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#797979',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'block',
        'operator' => '==',
        'value' => 'acf/three-column-news',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
  'acfe_display_title' => '',
  'acfe_autosync' => '',
  'acfe_form' => 0,
  'acfe_meta' => '',
  'acfe_note' => '',
));

endif;